Fix incorrect keyword argument in DMatrix creation
The instance weight parameter is incorrectly called weights in the DMatrix creation. As a result, if customers specify csv_weights=1 the container fails with algorithm error TypeError: __init__() got an unexpected keyword argument 'weights'